package web

import (
	"fmt"
	"strings"

	"github.com/go-pdf/fpdf"
)

// renderInvoicePDF builds a one-page A4 invoice for the given data.
// Layout is intentionally plain: heading, client, period, items table,
// total, notes. Branding stays minimal so it prints cleanly anywhere.
func renderInvoicePDF(inv invoiceVM, teamName string) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 18)
	pdf.AddPage()
	pdf.SetFont("Helvetica", "", 10)
	// Core fonts are cp1252: translate UTF-8 so "·", "–", "…" print.
	tr := pdf.UnicodeTranslatorFromDescriptor("")

	// Header
	pdf.SetFont("Helvetica", "B", 18)
	pdf.Cell(0, 9, "INVOICE")
	pdf.Ln(8)
	pdf.SetFont("Helvetica", "", 11)
	pdf.Cell(0, 6, tr(inv.Number))
	pdf.Ln(6)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 5, tr("From: "+teamName))
	pdf.Ln(5)
	pdf.SetTextColor(0, 0, 0)

	// Client block (right-ish)
	pdf.SetY(18)
	pdf.SetX(120)
	pdf.SetFont("Helvetica", "", 9)
	pdf.Cell(80, 5, "Billed to")
	pdf.SetX(120)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.Cell(80, 7, tr(inv.ClientName))
	pdf.SetX(120)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(80, 5, tr(inv.PeriodISO))
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(14)

	// Table header
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(245, 246, 248)
	pdf.CellFormat(90, 8, "Task", "1", 0, "L", true, 0, "")
	pdf.CellFormat(25, 8, "Hours", "1", 0, "R", true, 0, "")
	pdf.CellFormat(30, 8, "Rate", "1", 0, "R", true, 0, "")
	pdf.CellFormat(35, 8, "Amount", "1", 0, "R", true, 0, "")
	pdf.Ln(-1)

	// Lines
	pdf.SetFont("Helvetica", "", 9)
	for _, l := range inv.Lines {
		label := l.Label
		if pdf.GetStringWidth(label) > 85 {
			label = truncateRunes(label, 28) + "…"
		}
		pdf.CellFormat(90, 7, tr(label), "1", 0, "L", false, 0, "")
		pdf.CellFormat(25, 7, l.Hours, "1", 0, "R", false, 0, "")
		pdf.CellFormat(30, 7, l.Rate, "1", 0, "R", false, 0, "")
		pdf.CellFormat(35, 7, l.Amount, "1", 0, "R", false, 0, "")
		pdf.Ln(-1)
	}

	// Total
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(115, 9, tr("Total · "+inv.Hours), "1", 0, "R", false, 0, "")
	pdf.CellFormat(30, 9, "", "1", 0, "R", false, 0, "")
	pdf.CellFormat(35, 9, inv.Total, "1", 0, "R", false, 0, "")
	pdf.Ln(-1)

	// Notes
	if inv.Notes != "" {
		pdf.Ln(8)
		pdf.SetFont("Helvetica", "", 9)
		pdf.MultiCell(0, 5, "Notes: "+inv.Notes, "", "L", false)
	}
	if inv.PaymentURL != "" {
		pdf.Ln(4)
		pdf.SetFont("Helvetica", "", 9)
		pdf.Cell(0, 5, "Pay online: "+inv.PaymentURL)
		pdf.Ln(5)
	}

	pdf.Ln(6)
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetTextColor(130, 130, 130)
	pdf.Cell(0, 4, "Generated by paratrack from tracked time.")

	var buf strings.Builder
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return []byte(buf.String()), nil
}

// truncateRunes cuts a string to n runes (for PDF cells).
func truncateRunes(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n])
}

// invoicePDFName is the download filename.
func invoicePDFName(inv invoiceVM) string {
	return fmt.Sprintf("%s.pdf", strings.ReplaceAll(inv.Number, " ", "-"))
}
