import { Building2, Pencil, Plus, Trash2, Upload } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { DisclosureSection } from "@/components/disclosure-section"
import { translate as t } from "@/i18n"
import { SettingsNav, settingsTitle } from "@/settings/settings-nav"
import type { TeamSettingsData } from "@/dashboard/types"

export function TeamSettingsPage({ data }: { data: TeamSettingsData }) {
  const lang = data.Lang || "en"
  return <main className="mx-auto grid w-full max-w-6xl gap-4">
    <h1 className="text-2xl font-semibold tracking-tight">{settingsTitle(lang, data.Active)}</h1>
    <SettingsNav active={data.Active} lang={lang} canManage={data.CanManage} />
    {data.Flash && <p role={data.FlashOK ? "status" : "alert"} className={`rounded-md border p-3 text-sm ${data.FlashOK ? "border-border" : "border-destructive/40 text-destructive"}`}>{data.Flash}</p>}
    <div className="grid gap-4 lg:grid-cols-2 lg:items-start">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Building2 aria-hidden="true" />{t(lang, "team.current")}</CardTitle><p className="text-sm text-muted-foreground">{t(lang, "team.switchHint")}</p></CardHeader><CardContent><dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-1 text-sm"><dt className="text-muted-foreground">{t(lang, "team.nameCol")}</dt><dd>{data.Team.Name}</dd><dt className="text-muted-foreground">{t(lang, "team.createdCol")}</dt><dd>{data.Team.CreatedAt.slice(0, 10)}</dd></dl></CardContent></Card>
      <Card><CardHeader><CardTitle>{t(lang, "team.renameTitle")}</CardTitle></CardHeader><CardContent><form method="post" action="/api/team/rename" className="flex flex-col gap-2 sm:flex-row"><input type="hidden" name="csrf_token" value={data.CSRFToken} /><Label className="sr-only" htmlFor="team-name">{t(lang, "team.nameCol")}</Label><Input id="team-name" name="name" required minLength={1} defaultValue={data.Team.Name} className="flex-1" /><Button type="submit"><Pencil aria-hidden="true" />{t(lang, "team.rename")}</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle>{t(lang, "team.currencyTitle")}</CardTitle><p className="text-sm text-muted-foreground">{t(lang, "team.currencyHint")}</p></CardHeader><CardContent><form method="post" action="/api/team/currency" className="flex gap-2"><input type="hidden" name="csrf_token" value={data.CSRFToken} /><Label className="sr-only" htmlFor="team-currency">{t(lang, "team.currencyTitle")}</Label><Select name="currency" defaultValue={data.Currency}><SelectTrigger id="team-currency" className="flex-1"><SelectValue /></SelectTrigger><SelectContent>{data.Currencies.map(currency => <SelectItem key={currency.Code} value={currency.Code}>{currency.Label}</SelectItem>)}</SelectContent></Select><Button type="submit">{t(lang, "profile.save")}</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle>{t(lang, "team.createTitle")}</CardTitle><p className="text-sm text-muted-foreground">{t(lang, "team.createBlurb")}</p></CardHeader><CardContent><form method="post" action="/api/team/create" className="flex gap-2"><input type="hidden" name="csrf_token" value={data.CSRFToken} /><Label className="sr-only" htmlFor="team-new-name">{t(lang, "projects.name")}</Label><Input id="team-new-name" name="name" required minLength={1} placeholder={t(lang, "ph.team")} className="flex-1" /><Button type="submit"><Plus aria-hidden="true" />{t(lang, "projects.create")}</Button></form></CardContent></Card>
      <DisclosureSection className="lg:col-span-2" title={t(lang, "team.reqTitle")} description={t(lang, "team.reqHint")}><div className="grid gap-4"><form method="post" action="/api/team/requisites" className="grid gap-3"><input type="hidden" name="csrf_token" value={data.CSRFToken} /><div className="grid gap-1.5"><Label htmlFor="requisites">{t(lang, "team.reqLabel")}</Label><Textarea id="requisites" name="requisites" rows={6} maxLength={2000} className="font-mono text-sm" placeholder={t(lang, "team.reqPh")}>{data.Requisites}</Textarea></div><div className="grid gap-1.5"><Label htmlFor="vat-note">{t(lang, "team.vatLabel")}</Label><Input id="vat-note" name="vat_note" maxLength={200} defaultValue={data.VATNote} placeholder={t(lang, "team.vatPh")} /></div><Button type="submit" className="w-fit">{t(lang, "profile.save")}</Button></form></div></DisclosureSection>
      <DisclosureSection id="billing" defaultOpen={location.hash === "#billing"} className="lg:col-span-2" title={t(lang, "bill.title")} description={t(lang, "settings.billingHint")}><div className="grid gap-4">
        <form method="post" action="/api/team/billing" className="grid gap-3"><input type="hidden" name="csrf_token" value={data.CSRFToken} /><div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-1.5"><Label htmlFor="round-minutes">{t(lang, "bill.round")}</Label><Select name="round_minutes" defaultValue={String(data.Billing.RoundMinutes)}><SelectTrigger id="round-minutes"><SelectValue /></SelectTrigger><SelectContent>{data.RoundOpts.map(minutes => <SelectItem key={minutes} value={String(minutes)}>{minutes === 0 ? t(lang, "bill.roundOff") : t(lang, "bill.roundTo", minutes)}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-1.5"><Label htmlFor="round-mode">{t(lang, "bill.mode")}</Label><Select name="round_mode" defaultValue={data.Billing.RoundMode === "up" ? "up" : "nearest"}><SelectTrigger id="round-mode"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="nearest">{t(lang, "bill.nearest")}</SelectItem><SelectItem value="up">{t(lang, "bill.up")}</SelectItem></SelectContent></Select></div></div><p className="text-xs text-muted-foreground">{t(lang, "bill.roundHint")}</p><div className="grid gap-1.5"><Label htmlFor="invoice-prefix">{t(lang, "bill.prefix")}</Label><Input id="invoice-prefix" name="invoice_prefix" required maxLength={12} pattern="(?:\p{L}|\p{N}|-)+" defaultValue={data.Billing.InvoicePrefix} className="font-mono" /><p className="text-xs text-muted-foreground">{t(lang, "bill.prefixHint", data.Billing.InvoicePrefix)}</p></div><Button type="submit" className="w-fit">{t(lang, "profile.save")}</Button></form>
        <div className="grid gap-2 border-t pt-3"><Label htmlFor="team-logo">{t(lang, "bill.logo")}</Label>{data.Billing.HasLogo && <img src={data.LogoURL} alt={t(lang, "bill.logo")} className="max-h-14 max-w-48 rounded border bg-white p-1 object-contain" />}<form method="post" action="/api/team/logo" encType="multipart/form-data" className="flex flex-wrap items-center gap-2"><input type="hidden" name="csrf_token" value={data.CSRFToken} /><Input id="team-logo" type="file" name="logo" accept="image/png,image/jpeg" required className="min-w-0 flex-1" /><Button type="submit" size="sm"><Upload aria-hidden="true" />{t(lang, "bill.upload")}</Button></form>{data.Billing.HasLogo && <form method="post" action="/api/team/logo"><input type="hidden" name="csrf_token" value={data.CSRFToken} /><input type="hidden" name="remove" value="1" /><Button type="submit" size="sm" variant="ghost">{t(lang, "bill.removeLogo")}</Button></form>}<p className="text-xs text-muted-foreground">{t(lang, "bill.logoHint")}</p></div>
      </div></DisclosureSection>

      <DisclosureSection className="lg:col-span-2" title={t(lang, "stripe.title")} description={t(lang, "stripe.blurb")}><div className="grid gap-4"><form method="post" action="/api/team/stripe" className="grid gap-3"><input type="hidden" name="csrf_token" value={data.CSRFToken} /><div className="grid gap-1.5"><Label htmlFor="stripe-key">{t(lang, "stripe.keyLabel")}</Label><Input id="stripe-key" type="password" name="stripe_key" autoComplete="off" placeholder="sk_live_… / sk_test_…" /><p className="text-xs text-muted-foreground">{t(lang, "stripe.keyHint")}</p></div><div className="grid gap-1.5"><Label htmlFor="stripe-webhook-secret">{t(lang, "stripe.whLabel")}</Label><Input id="stripe-webhook-secret" type="password" name="stripe_webhook_secret" autoComplete="off" placeholder="whsec_…" /><p className="text-xs text-muted-foreground">{t(lang, "stripe.whHint")}</p></div><Button type="submit" className="w-fit">{t(lang, "stripe.save")}</Button></form><p className="text-xs text-muted-foreground">{t(lang, "stripe.hint")}</p></div></DisclosureSection>
      <DisclosureSection className="lg:col-span-2" title={t(lang, "team.danger")} description={t(lang, "team.dangerBlurb")}><div className="grid gap-4"><form method="post" action="/api/team/delete" data-confirm={t(lang, "team.confirmDelete")}><input type="hidden" name="csrf_token" value={data.CSRFToken} /><Button type="submit" variant="destructive" size="sm"><Trash2 aria-hidden="true" />{t(lang, "team.delete")}</Button></form></div></DisclosureSection>
    </div>
  </main>
}
