package db

import (
	"database/sql"
	"fmt"
	"math/rand"
	"regexp"
	"strings"
	"time"
)

// The Postgres schema is derived from the SQLite one at startup, so there
// is a single source of truth. pgDDL maps the few SQLite-isms it uses.
var (
	reAutoinc  = regexp.MustCompile(`INTEGER PRIMARY KEY AUTOINCREMENT`)
	reNowText  = regexp.MustCompile(`\(strftime\('%Y-%m-%dT%H:%M:%f', 'now'\)\)`)
	reNocase   = regexp.MustCompile(`TEXT NOT NULL COLLATE NOCASE`)
	reIdxCase  = regexp.MustCompile(`\((\w+) COLLATE NOCASE\)`)
	reInteger  = regexp.MustCompile(`\bINTEGER\b`)
	pgNowText  = `(to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS'))`
	pgIdentity = `BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`
)

func pgDDL(s string) string {
	s = reAutoinc.ReplaceAllString(s, pgIdentity)
	s = reNowText.ReplaceAllString(s, pgNowText)
	// Case-insensitive columns become CITEXT: equality, UNIQUE and ORDER BY
	// all ignore case, exactly like SQLite's COLLATE NOCASE.
	s = reNocase.ReplaceAllString(s, "CITEXT NOT NULL")
	s = reIdxCase.ReplaceAllString(s, "($1)")
	// reminders.window: WINDOW is reserved in Postgres.
	s = strings.Replace(s, "    window TEXT,", `    "window" TEXT,`, 1)
	return reInteger.ReplaceAllString(s, "BIGINT")
}

// applyPostgresSchema creates or upgrades the Postgres schema. Every
// statement is idempotent, so it runs on each start like the SQLite path.
func (d *DB) applyPostgresSchema() error {
	stmts := []string{
		`CREATE EXTENSION IF NOT EXISTS citext`,
		pgDDL(schema),
		// Only an expression index made these case-insensitive in SQLite.
		`ALTER TABLE users ALTER COLUMN email TYPE CITEXT`,
		`ALTER TABLE teams ALTER COLUMN slug TYPE CITEXT`,
	}
	for _, m := range columnMigrations {
		stmts = append(stmts, "ALTER TABLE "+m.table+" ADD COLUMN IF NOT EXISTS "+m.column+" "+pgDDL(m.decl))
	}
	for _, m := range uniqueMigrations {
		stmts = append(stmts, pgDDL(m))
	}
	for _, s := range stmts {
		if strings.TrimSpace(s) == "" {
			continue
		}
		// Straight to *sql.DB: DDL has no placeholders to rebind, and the
		// no-argument path lets pgx run the multi-statement schema at once.
		if _, err := d.sql.DB.Exec(s); err != nil {
			return err
		}
	}
	return nil
}

// openTestPostgres gives each test its own throwaway schema on the
// PARATRACK_TEST_PG server (search_path keeps citext from public).
func openTestPostgres(url string) (*DB, error) {
	admin, err := sql.Open("pgx", url)
	if err != nil {
		return nil, err
	}
	defer admin.Close()
	name := fmt.Sprintf("t_%d_%d", time.Now().UnixNano(), rand.Int63())
	if _, err := admin.Exec(`CREATE EXTENSION IF NOT EXISTS citext`); err != nil {
		return nil, err
	}
	if _, err := admin.Exec(`CREATE SCHEMA ` + name); err != nil {
		return nil, err
	}
	sep := "?"
	if strings.Contains(url, "?") {
		sep = "&"
	}
	return OpenPostgres(url + sep + "search_path=" + name + ",public")
}
