package db

import "strings"

// schema is the full Postgres DDL. Every statement is idempotent, so it
// runs on each start; columnMigrations and uniqueMigrations bring older
// databases up to date. Timestamps are TEXT (RFC3339Nano UTC, see
// FormatTime); case-insensitive names are CITEXT.
const schema = `
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS'))
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_users_email ON users(email);

CREATE TABLE IF NOT EXISTS auth_sessions (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    expires_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id);

CREATE TABLE IF NOT EXISTS teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL,
    name TEXT NOT NULL,
    owner_id BIGINT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_teams_slug ON teams(slug);

CREATE TABLE IF NOT EXISTS memberships (
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('owner', 'admin', 'member')),
    joined_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    PRIMARY KEY (team_id, user_id),
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships(user_id);

CREATE TABLE IF NOT EXISTS invites (
    token TEXT PRIMARY KEY,
    team_id BIGINT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member' CHECK(role IN ('owner', 'member')),
    created_by BIGINT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    expires_at TEXT NOT NULL,
    accepted_at TEXT,
    accepted_by BIGINT,
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (accepted_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_invites_team ON invites(team_id);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    slug CITEXT NOT NULL,
    name TEXT NOT NULL,
    color TEXT NOT NULL DEFAULT '#7c8499',
    archived BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    UNIQUE (team_id, slug)
);
CREATE INDEX IF NOT EXISTS idx_projects_team ON projects(team_id);

CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CITEXT NOT NULL,
    team_id BIGINT,
    project_id BIGINT,
    archived BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_activities_team ON activities(team_id);
CREATE INDEX IF NOT EXISTS idx_activities_name ON activities(name);

CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT NOT NULL,
    team_id BIGINT,
    start_at TEXT NOT NULL,
    end_at TEXT,
    note TEXT,
    paused BIGINT NOT NULL DEFAULT 0,
    paused_at TEXT,
    accumulated_seconds BIGINT NOT NULL DEFAULT 0,
    last_resume_at TEXT,
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE,
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sessions_activity ON sessions(activity_id);
CREATE INDEX IF NOT EXISTS idx_sessions_team     ON sessions(team_id);
CREATE INDEX IF NOT EXISTS idx_sessions_start    ON sessions(start_at);
CREATE INDEX IF NOT EXISTS idx_sessions_end      ON sessions(end_at);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CITEXT NOT NULL,
    team_id BIGINT,
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    UNIQUE (team_id, name)
);
CREATE INDEX IF NOT EXISTS idx_tags_team ON tags(team_id);
CREATE INDEX IF NOT EXISTS idx_tags_name ON tags(name);

CREATE TABLE IF NOT EXISTS session_tags (
    session_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (session_id, tag_id),
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_session_tags_session ON session_tags(session_id);
CREATE INDEX IF NOT EXISTS idx_session_tags_tag     ON session_tags(tag_id);

CREATE TABLE IF NOT EXISTS goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL DEFAULT 0,
    period TEXT NOT NULL CHECK(period IN ('daily', 'weekly', 'monthly')),
    target_minutes BIGINT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE,
    UNIQUE (team_id, activity_id, period)
);
CREATE INDEX IF NOT EXISTS idx_goals_team ON goals(team_id);

CREATE TABLE IF NOT EXISTS reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT NOT NULL,
    every_minutes BIGINT NOT NULL,
    "window" TEXT,
    enabled BIGINT NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
    FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    used_at TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens(user_id);

CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    number TEXT NOT NULL,
    client_name TEXT NOT NULL DEFAULT '',
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    notes TEXT NOT NULL DEFAULT '',
    payment_url TEXT DEFAULT '',
    stripe_session_id TEXT DEFAULT '',
    paid_at TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    UNIQUE (team_id, number)
);
CREATE INDEX IF NOT EXISTS idx_invoices_team ON invoices(team_id);

CREATE TABLE IF NOT EXISTS invoice_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    label TEXT NOT NULL,
    detail TEXT NOT NULL DEFAULT '',
    seconds BIGINT NOT NULL DEFAULT 0,
    rate_cents BIGINT NOT NULL DEFAULT 0,
    amount_cents BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_invoice_lines_invoice ON invoice_lines(invoice_id);


CREATE TABLE IF NOT EXISTS payroll_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    number TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    notes TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    UNIQUE (team_id, number)
);
CREATE INDEX IF NOT EXISTS idx_payroll_runs_team ON payroll_runs(team_id);

CREATE TABLE IF NOT EXISTS payroll_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    label TEXT NOT NULL DEFAULT '',
    seconds BIGINT NOT NULL DEFAULT 0,
    rate_cents BIGINT NOT NULL DEFAULT 0,
    amount_cents BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (run_id) REFERENCES payroll_runs(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_payroll_lines_run ON payroll_lines(run_id);

CREATE TABLE IF NOT EXISTS schedule_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    day TEXT NOT NULL,
    minutes BIGINT NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    UNIQUE (team_id, user_id, project_id, day)
);
CREATE INDEX IF NOT EXISTS idx_schedule_team ON schedule_entries(team_id, day);

CREATE TABLE IF NOT EXISTS push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    endpoint TEXT NOT NULL UNIQUE,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_push_subs_team ON push_subscriptions(team_id);

CREATE TABLE IF NOT EXISTS push_keys (
    id BIGINT PRIMARY KEY CHECK (id = 1),
    public_key TEXT NOT NULL,
    private_key TEXT NOT NULL
);

`

// columnMigrations ensures older databases (e.g. created before pause/resume
// support) get the required columns added. Safe to run repeatedly.
var columnMigrations = []struct {
	table  string
	column string
	decl   string
}{
	{"sessions", "paused", "BIGINT NOT NULL DEFAULT 0"},
	{"sessions", "paused_at", "TEXT"},
	{"sessions", "accumulated_seconds", "BIGINT NOT NULL DEFAULT 0"},
	{"sessions", "last_resume_at", "TEXT"},
	{"activities", "project_id", "BIGINT"},
	// Estimates vs actual (Wave 1).
	{"projects", "estimate_minutes", "BIGINT"},
	{"projects", "billable_rate_cents", "BIGINT"},
	{"projects", "billable", "BIGINT NOT NULL DEFAULT 1"},
	{"teams", "stripe_key", "TEXT"},
	{"teams", "stripe_webhook_secret", "TEXT"},
	{"invoices", "payment_url", "TEXT"},
	{"invoices", "stripe_session_id", "TEXT"},
	{"invoices", "paid_at", "TEXT"},
	{"sessions", "user_id", "BIGINT"},
	{"memberships", "hourly_pay_cents", "BIGINT"},
	{"memberships", "capacity_minutes", "BIGINT"},
	// Currency: the workspace default, a project override ('' = inherit),
	// and the currency fixed on each document when it is created.
	{"teams", "currency", "TEXT NOT NULL DEFAULT 'RUB'"},
	{"projects", "currency", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "currency", "TEXT NOT NULL DEFAULT ''"},
	{"payroll_runs", "currency", "TEXT NOT NULL DEFAULT ''"},
	// Imported history: "toggl:123" etc., so a re-import adds nothing twice.
	{"sessions", "external_id", "TEXT"},
	// Document details: the issuer's requisites and VAT line on the
	// workspace, copied onto each invoice with the client's own details.
	{"teams", "requisites", "TEXT NOT NULL DEFAULT ''"},
	{"teams", "vat_note", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "seller_details", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "client_details", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "vat_note", "TEXT NOT NULL DEFAULT ''"},
	// Freelancer flow: a project remembers its client (name, details,
	// email) for the next invoice; a billed session points at its invoice
	// so it isn't billed twice and can't change under a sent document;
	// a paid invoice can carry the "Мой налог" receipt.
	{"projects", "client_name", "TEXT NOT NULL DEFAULT ''"},
	{"projects", "client_details", "TEXT NOT NULL DEFAULT ''"},
	{"projects", "client_email", "TEXT NOT NULL DEFAULT ''"},
	{"sessions", "invoice_id", "BIGINT"},
	{"invoices", "project_id", "BIGINT"},
	{"invoices", "client_email", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "receipt", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "by_person", "BIGINT NOT NULL DEFAULT 0"}, // lines split per team member
	// Personal preferences (JSON, see web/prefs.go).
	{"users", "prefs", "TEXT NOT NULL DEFAULT ''"},
	// Billing rules: round each invoice line to N minutes (0 = 0.01 h),
	// "up" or "nearest"; invoice number prefix; logo for documents.
	{"teams", "round_minutes", "BIGINT NOT NULL DEFAULT 0"},
	{"teams", "round_mode", "TEXT NOT NULL DEFAULT 'nearest'"},
	{"teams", "invoice_prefix", "TEXT NOT NULL DEFAULT 'INV'"},
	{"teams", "logo", "TEXT NOT NULL DEFAULT ''"},
	// Sections the workspace uses ("" = all, "none" = core only).
	{"teams", "modules", "TEXT NOT NULL DEFAULT ''"},
	// Activity lookup key: lowercase in Go (Unicode), the name keeps case.
	{"activities", "name_key", "TEXT"},
	// API tokens: the workspace they act in, optional expiry, read-only.
	{"api_tokens", "team_id", "BIGINT"},
	{"api_tokens", "expires_at", "TEXT"},
	{"api_tokens", "read_only", "BIGINT NOT NULL DEFAULT 0"},
}

// uniqueMigrations creates UNIQUE / lookup indexes that the original
// schema didn't include or that depend on a column being added by
// columnMigrations. Each entry is idempotent: IF NOT EXISTS lets us
// run it on every startup without harm.
//
// Note: the goal-uniqueness guarantee now lives in the CREATE TABLE
// clause (`UNIQUE (team_id, activity_id, period)`); the historical
// (activity_id, period) index is intentionally not recreated here
// because it would conflict with the ON CONFLICT(team_id, activity_id,
// period) DO UPDATE used by UpsertGoal.
var uniqueMigrations = []string{
	// Big teams: every member view filters team + person + time; the
	// unbilled total wants closed sessions not on an invoice.
	`CREATE INDEX IF NOT EXISTS idx_sessions_team_start ON sessions(team_id, start_at)`,
	`CREATE INDEX IF NOT EXISTS idx_sessions_team_user_start ON sessions(team_id, user_id, start_at)`,
	`CREATE INDEX IF NOT EXISTS idx_sessions_activity_start ON sessions(activity_id, start_at)`,
	`CREATE INDEX IF NOT EXISTS idx_sessions_invoice ON sessions(invoice_id) WHERE invoice_id IS NOT NULL`,
	`CREATE INDEX IF NOT EXISTS idx_sessions_unbilled ON sessions(team_id, activity_id) INCLUDE (start_at, end_at, accumulated_seconds) WHERE invoice_id IS NULL AND end_at IS NOT NULL`,
	`CREATE INDEX IF NOT EXISTS idx_activities_key ON activities(team_id, name_key)`,
	// Someone who left keeps their pay rate for the time they worked, so
	// the next pay run still pays it.
	`CREATE TABLE IF NOT EXISTS former_members (
	    team_id BIGINT NOT NULL,
	    user_id BIGINT NOT NULL,
	    hourly_pay_cents BIGINT,
	    left_at TEXT NOT NULL,
	    PRIMARY KEY (team_id, user_id)
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_external ON sessions(team_id, external_id) WHERE external_id IS NOT NULL`,
	`CREATE INDEX IF NOT EXISTS idx_activities_project ON activities(project_id)`,
	// Older DBs predate the password-reset table; IF NOT EXISTS makes
	// this safe to re-run on every startup.
	`CREATE TABLE IF NOT EXISTS password_reset_tokens (
	    token TEXT PRIMARY KEY,
	    user_id BIGINT NOT NULL,
	    created_at TEXT NOT NULL,
	    expires_at TEXT NOT NULL,
	    used_at TEXT,
	    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens(user_id)`,
	// Saved /stats filter presets (Wave 1).
	`CREATE TABLE IF NOT EXISTS saved_reports (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    name TEXT NOT NULL,
	    period TEXT NOT NULL DEFAULT 'today',
	    project_slug TEXT NOT NULL DEFAULT '',
	    tag TEXT NOT NULL DEFAULT '',
	    created_by BIGINT,
	    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
	    UNIQUE (team_id, name)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_saved_reports_team ON saved_reports(team_id)`,
	// Wave 2: API tokens (extension / CLI bearer auth).
	`CREATE TABLE IF NOT EXISTS api_tokens (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    user_id BIGINT NOT NULL,
	    name TEXT NOT NULL,
	    token_hash TEXT NOT NULL UNIQUE,
	    prefix TEXT NOT NULL,
	    created_at TEXT NOT NULL,
	    last_used_at TEXT,
	    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_api_tokens_user ON api_tokens(user_id)`,
	// Wave 2: integrations (github / trello).
	`CREATE TABLE IF NOT EXISTS integrations (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    provider TEXT NOT NULL,
	    name TEXT NOT NULL,
	    secret TEXT NOT NULL DEFAULT '',
	    config TEXT NOT NULL DEFAULT '{}',
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
	    UNIQUE (team_id, provider, name)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_integrations_team ON integrations(team_id)`,
	// External work items imported from an integration.
	`CREATE TABLE IF NOT EXISTS external_tasks (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    integration_id BIGINT NOT NULL,
	    external_id TEXT NOT NULL,
	    title TEXT NOT NULL,
	    url TEXT NOT NULL DEFAULT '',
	    status TEXT NOT NULL DEFAULT 'open',
	    activity_id BIGINT,
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (integration_id) REFERENCES integrations(id) ON DELETE CASCADE,
	    FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE SET NULL,
	    UNIQUE (integration_id, external_id)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_external_tasks_integration ON external_tasks(integration_id)`,
	// Wave 3: invoices.
	`CREATE TABLE IF NOT EXISTS invoices (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    number TEXT NOT NULL,
	    client_name TEXT NOT NULL DEFAULT '',
	    period_start TEXT NOT NULL,
	    period_end TEXT NOT NULL,
	    status TEXT NOT NULL DEFAULT 'draft',
	    notes TEXT NOT NULL DEFAULT '',
	    payment_url TEXT DEFAULT '',
	    stripe_session_id TEXT DEFAULT '',
	    paid_at TEXT,
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
	    UNIQUE (team_id, number)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_invoices_team ON invoices(team_id)`,
	`CREATE TABLE IF NOT EXISTS invoice_lines (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    invoice_id BIGINT NOT NULL,
	    label TEXT NOT NULL,
	    detail TEXT NOT NULL DEFAULT '',
	    seconds BIGINT NOT NULL DEFAULT 0,
	    rate_cents BIGINT NOT NULL DEFAULT 0,
	    amount_cents BIGINT NOT NULL DEFAULT 0,
	    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_invoice_lines_invoice ON invoice_lines(invoice_id)`,
	// Wave 4: audit log (enterprise).
	`CREATE TABLE IF NOT EXISTS audit_log (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL DEFAULT 0,
	    user_id BIGINT NOT NULL DEFAULT 0,
	    action TEXT NOT NULL,
	    target TEXT NOT NULL DEFAULT '',
	    meta TEXT NOT NULL DEFAULT '',
	    ip TEXT NOT NULL DEFAULT '',
	    created_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_audit_log_team ON audit_log(team_id, created_at)`,
	// Wave 4: outbound webhooks.
	`CREATE TABLE IF NOT EXISTS webhooks (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    url TEXT NOT NULL,
	    secret TEXT NOT NULL DEFAULT '',
	    events TEXT NOT NULL DEFAULT 'session.stopped,invoice.created',
	    active BIGINT NOT NULL DEFAULT 1,
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_webhooks_team ON webhooks(team_id)`,
	`CREATE TABLE IF NOT EXISTS webhook_deliveries (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    webhook_id BIGINT NOT NULL,
	    event TEXT NOT NULL,
	    payload TEXT NOT NULL,
	    status BIGINT NOT NULL DEFAULT 0,
	    error TEXT NOT NULL DEFAULT '',
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_webhook_deliveries ON webhook_deliveries(webhook_id)`,
}

// applySchema creates or upgrades the schema. Every statement is
// idempotent, so it runs on each start.
func (d *DB) applySchema() error {
	stmts := []string{
		`CREATE EXTENSION IF NOT EXISTS citext`,
		schema,
		// Older databases had these as TEXT with a case-insensitive index.
		`ALTER TABLE users ALTER COLUMN email TYPE CITEXT`,
		`ALTER TABLE teams ALTER COLUMN slug TYPE CITEXT`,
		// Roles grew an admin; recreate the CHECK (idempotent).
		`ALTER TABLE memberships DROP CONSTRAINT IF EXISTS memberships_role_check`,
		`ALTER TABLE memberships ADD CONSTRAINT memberships_role_check CHECK (role IN ('owner', 'admin', 'member'))`,
	}
	// Columns go in twice: some tables (api_tokens …) are only created by
	// uniqueMigrations, and some of their indexes need the columns.
	cols := func() {
		for _, m := range columnMigrations {
			stmts = append(stmts, "ALTER TABLE IF EXISTS "+m.table+" ADD COLUMN IF NOT EXISTS "+m.column+" "+m.decl)
		}
	}
	cols()
	stmts = append(stmts, uniqueMigrations...)
	cols()
	// Closed sessions carry their tracked total (older ones left it 0 and
	// had it recomputed from the text timestamps on every read). Same
	// number DurationSeconds gives: whole seconds of the span.
	stmts = append(stmts, `UPDATE sessions SET accumulated_seconds =
		GREATEST(0, FLOOR(EXTRACT(EPOCH FROM (end_at::timestamp - start_at::timestamp))))::bigint
		WHERE end_at IS NOT NULL AND accumulated_seconds = 0 AND end_at > start_at`)
	// A session's invoice is a real reference: deleting the invoice frees
	// the session, so "not billed" is just invoice_id IS NULL.
	stmts = append(stmts,
		`UPDATE sessions SET invoice_id = NULL WHERE invoice_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM invoices i WHERE i.id = sessions.invoice_id)`,
		`DO $$ BEGIN
		   IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sessions_invoice_id_fkey') THEN
		     ALTER TABLE sessions ADD CONSTRAINT sessions_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL;
		   END IF;
		 END $$`,
	)
	for _, s := range stmts {
		// Straight to *sql.DB: DDL has no placeholders to rebind, and the
		// no-argument path lets pgx run the multi-statement schema at once.
		if _, err := d.sql.DB.Exec(s); err != nil {
			return err
		}
	}
	return nil
}

// caseRow is an (id, name) pair.
type caseRow struct {
	id   int64
	name string
}

// fillActivityKeys sets name_key for rows made before it existed.
func (d *DB) fillActivityKeys() error {
	rows, err := d.sql.Query(`SELECT id, name FROM activities WHERE name_key IS NULL`)
	if err != nil {
		return err
	}
	var todo []caseRow
	for rows.Next() {
		var r caseRow
		if err := rows.Scan(&r.id, &r.name); err != nil {
			rows.Close()
			return err
		}
		todo = append(todo, r)
	}
	rows.Close()
	for _, r := range todo {
		if _, err := d.sql.Exec(`UPDATE activities SET name_key = ? WHERE id = ?`, strings.ToLower(r.name), r.id); err != nil {
			return err
		}
	}
	return nil
}
