package db

// columnMigrations ensures older databases (e.g. created before pause/resume
// support) get the required columns added. Safe to run repeatedly.
var columnMigrations = []struct {
	table  string
	column string
	decl   string
}{
	{"sessions", "paused", "BIGINT NOT NULL DEFAULT 0"},
	{"sessions", "paused_at", "TEXT"},
	{"sessions", "accumulated_seconds", "BIGINT NOT NULL DEFAULT 0"},
	{"sessions", "last_resume_at", "TEXT"},
	{"activities", "project_id", "BIGINT"},
	// Estimates vs actual (Wave 1).
	{"projects", "estimate_minutes", "BIGINT"},
	{"projects", "billable_rate_cents", "BIGINT"},
	{"projects", "billable", "BIGINT NOT NULL DEFAULT 1"},
	{"teams", "stripe_key", "TEXT"},
	{"teams", "stripe_webhook_secret", "TEXT"},
	{"invoices", "payment_url", "TEXT"},
	{"invoices", "stripe_session_id", "TEXT"},
	{"invoices", "paid_at", "TEXT"},
	{"sessions", "user_id", "BIGINT"},
	{"memberships", "hourly_pay_cents", "BIGINT"},
	{"memberships", "capacity_minutes", "BIGINT"},
	// Currency: the workspace default, a project override ('' = inherit),
	// and the currency fixed on each document when it is created.
	{"teams", "currency", "TEXT NOT NULL DEFAULT 'RUB'"},
	{"projects", "currency", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "currency", "TEXT NOT NULL DEFAULT ''"},
	{"payroll_runs", "currency", "TEXT NOT NULL DEFAULT ''"},
	// Imported history: "toggl:123" etc., so a re-import adds nothing twice.
	{"sessions", "external_id", "TEXT"},
	// Document details: the issuer's requisites and VAT line on the
	// workspace, copied onto each invoice with the client's own details.
	{"teams", "requisites", "TEXT NOT NULL DEFAULT ''"},
	{"teams", "vat_note", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "seller_details", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "client_details", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "vat_note", "TEXT NOT NULL DEFAULT ''"},
	// Freelancer flow: a project remembers its client (name, details,
	// email) for the next invoice; a billed session points at its invoice
	// so it isn't billed twice and can't change under a sent document;
	// a paid invoice can carry the "Мой налог" receipt.
	{"projects", "client_name", "TEXT NOT NULL DEFAULT ''"},
	{"projects", "client_details", "TEXT NOT NULL DEFAULT ''"},
	{"projects", "client_email", "TEXT NOT NULL DEFAULT ''"},
	{"sessions", "invoice_id", "BIGINT"},
	{"invoices", "project_id", "BIGINT"},
	{"invoices", "client_email", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "receipt", "TEXT NOT NULL DEFAULT ''"},
	{"invoices", "by_person", "BIGINT NOT NULL DEFAULT 0"}, // lines split per team member
	{"invoices", "revision", "BIGINT NOT NULL DEFAULT 1"},
	{"invoice_stripe_sessions", "active", "BIGINT NOT NULL DEFAULT 1"},
	// Personal preferences (JSON, see web/prefs.go).
	{"users", "prefs", "TEXT NOT NULL DEFAULT ''"},
	// Billing rules: round each invoice line to N minutes (0 = 0.01 h),
	// "up" or "nearest"; invoice number prefix; logo for documents.
	{"teams", "round_minutes", "BIGINT NOT NULL DEFAULT 0"},
	{"teams", "round_mode", "TEXT NOT NULL DEFAULT 'nearest'"},
	{"teams", "invoice_prefix", "TEXT NOT NULL DEFAULT 'INV'"},
	{"teams", "logo", "TEXT NOT NULL DEFAULT ''"},
	// Sections the workspace uses ("" = all, "none" = core only).
	{"teams", "modules", "TEXT NOT NULL DEFAULT ''"},
	// Activity lookup key: lowercase in Go (Unicode), the name keeps case.
	{"activities", "name_key", "TEXT"},
	// API tokens: the workspace they act in, optional expiry, read-only.
	{"api_tokens", "team_id", "BIGINT"},
	{"api_tokens", "expires_at", "TEXT"},
	{"api_tokens", "read_only", "BIGINT NOT NULL DEFAULT 0"},
	{"webhook_event_outbox", "webhook_ids", "TEXT NOT NULL DEFAULT ''"},
	{"invites", "sealed_token", "TEXT NOT NULL DEFAULT ''"},
	{"integrations", "sync_generation", "BIGINT NOT NULL DEFAULT 0"},
}

// compatibilityStatements create or update schema objects introduced after
// the original database schema. They are idempotent and run on every startup.
var compatibilityStatements = []string{
	`CREATE TABLE IF NOT EXISTS invoice_email_outbox (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    invoice_id BIGINT NOT NULL,
	    recipient TEXT NOT NULL,
	    payload TEXT NOT NULL,
	    status TEXT NOT NULL DEFAULT 'pending',
	    attempts BIGINT NOT NULL DEFAULT 0,
	    available_at TEXT NOT NULL,
	    locked_at TEXT,
	    last_error TEXT NOT NULL DEFAULT '',
	    created_at TEXT NOT NULL,
	    completed_at TEXT,
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
	    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_invoice_email_active ON invoice_email_outbox(invoice_id) WHERE status IN ('pending', 'processing')`,
	`CREATE INDEX IF NOT EXISTS idx_invoice_email_claim ON invoice_email_outbox(status, available_at)`,
	`CREATE TABLE IF NOT EXISTS invoice_stripe_sessions (
	    stripe_session_id TEXT PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    invoice_id BIGINT NOT NULL,
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
	    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_invoice_stripe_sessions_invoice ON invoice_stripe_sessions(invoice_id)`,
	// Big teams: every member view filters team + person + time; the
	// unbilled total wants closed sessions not on an invoice.
	`CREATE INDEX IF NOT EXISTS idx_sessions_team_start ON sessions(team_id, start_at)`,
	`CREATE INDEX IF NOT EXISTS idx_sessions_team_user_start ON sessions(team_id, user_id, start_at)`,
	`CREATE INDEX IF NOT EXISTS idx_sessions_activity_start ON sessions(activity_id, start_at)`,
	`CREATE INDEX IF NOT EXISTS idx_sessions_invoice ON sessions(invoice_id) WHERE invoice_id IS NOT NULL`,
	`CREATE INDEX IF NOT EXISTS idx_sessions_unbilled ON sessions(team_id, activity_id) INCLUDE (start_at, end_at, accumulated_seconds) WHERE invoice_id IS NULL AND end_at IS NOT NULL`,
	`CREATE INDEX IF NOT EXISTS idx_activities_key ON activities(team_id, name_key)`,
	// Someone who left keeps their pay rate for the time they worked, so
	// the next pay run still pays it.
	`CREATE TABLE IF NOT EXISTS former_members (
	    team_id BIGINT NOT NULL,
	    user_id BIGINT NOT NULL,
	    hourly_pay_cents BIGINT,
	    left_at TEXT NOT NULL,
	    PRIMARY KEY (team_id, user_id)
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_external ON sessions(team_id, external_id) WHERE external_id IS NOT NULL`,
	`CREATE INDEX IF NOT EXISTS idx_activities_project ON activities(project_id)`,
	// Older DBs predate the password-reset table; IF NOT EXISTS makes
	// this safe to re-run on every startup.
	`CREATE TABLE IF NOT EXISTS password_reset_tokens (
	    token TEXT PRIMARY KEY,
	    user_id BIGINT NOT NULL,
	    created_at TEXT NOT NULL,
	    expires_at TEXT NOT NULL,
	    used_at TEXT,
	    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens(user_id)`,
	// Saved /stats filter presets (Wave 1).
	`CREATE TABLE IF NOT EXISTS saved_reports (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    name TEXT NOT NULL,
	    period TEXT NOT NULL DEFAULT 'today',
	    project_slug TEXT NOT NULL DEFAULT '',
	    tag TEXT NOT NULL DEFAULT '',
	    created_by BIGINT,
	    created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS')),
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
	    UNIQUE (team_id, name)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_saved_reports_team ON saved_reports(team_id)`,
	// Wave 2: API tokens (extension / CLI bearer auth).
	`CREATE TABLE IF NOT EXISTS api_tokens (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    user_id BIGINT NOT NULL,
	    name TEXT NOT NULL,
	    token_hash TEXT NOT NULL UNIQUE,
	    prefix TEXT NOT NULL,
	    created_at TEXT NOT NULL,
	    last_used_at TEXT,
	    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_api_tokens_user ON api_tokens(user_id)`,
	// Wave 2: integrations (github / trello).
	`CREATE TABLE IF NOT EXISTS integrations (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    provider TEXT NOT NULL,
	    name TEXT NOT NULL,
	    secret TEXT NOT NULL DEFAULT '',
	    config TEXT NOT NULL DEFAULT '{}',
	    sync_generation BIGINT NOT NULL DEFAULT 0,
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
	    UNIQUE (team_id, provider, name)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_integrations_team ON integrations(team_id)`,
	// External work items imported from an integration.
	`CREATE TABLE IF NOT EXISTS external_tasks (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    integration_id BIGINT NOT NULL,
	    external_id TEXT NOT NULL,
	    title TEXT NOT NULL,
	    url TEXT NOT NULL DEFAULT '',
	    status TEXT NOT NULL DEFAULT 'open',
	    activity_id BIGINT,
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (integration_id) REFERENCES integrations(id) ON DELETE CASCADE,
	    FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE SET NULL,
	    UNIQUE (integration_id, external_id)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_external_tasks_integration ON external_tasks(integration_id)`,
	// Wave 3: invoices.
	`CREATE TABLE IF NOT EXISTS invoices (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    number TEXT NOT NULL,
	    client_name TEXT NOT NULL DEFAULT '',
	    period_start TEXT NOT NULL,
	    period_end TEXT NOT NULL,
	    status TEXT NOT NULL DEFAULT 'draft',
	    notes TEXT NOT NULL DEFAULT '',
	    payment_url TEXT DEFAULT '',
	    stripe_session_id TEXT DEFAULT '',
	    paid_at TEXT,
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
	    UNIQUE (team_id, number)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_invoices_team ON invoices(team_id)`,
	`CREATE TABLE IF NOT EXISTS invoice_lines (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    invoice_id BIGINT NOT NULL,
	    label TEXT NOT NULL,
	    detail TEXT NOT NULL DEFAULT '',
	    seconds BIGINT NOT NULL DEFAULT 0,
	    rate_cents BIGINT NOT NULL DEFAULT 0,
	    amount_cents BIGINT NOT NULL DEFAULT 0,
	    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_invoice_lines_invoice ON invoice_lines(invoice_id)`,
	// Wave 4: audit log (enterprise).
	`CREATE TABLE IF NOT EXISTS audit_log (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL DEFAULT 0,
	    user_id BIGINT NOT NULL DEFAULT 0,
	    action TEXT NOT NULL,
	    target TEXT NOT NULL DEFAULT '',
	    meta TEXT NOT NULL DEFAULT '',
	    ip TEXT NOT NULL DEFAULT '',
	    created_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_audit_log_team ON audit_log(team_id, created_at)`,
	// Wave 4: outbound webhooks.
	`CREATE TABLE IF NOT EXISTS webhooks (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    url TEXT NOT NULL,
	    secret TEXT NOT NULL DEFAULT '',
	    events TEXT NOT NULL DEFAULT 'session.stopped,invoice.created',
	    active BIGINT NOT NULL DEFAULT 1,
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_webhooks_team ON webhooks(team_id)`,
	`CREATE TABLE IF NOT EXISTS webhook_deliveries (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    webhook_id BIGINT NOT NULL,
	    event TEXT NOT NULL,
	    payload TEXT NOT NULL,
	    status BIGINT NOT NULL DEFAULT 0,
	    error TEXT NOT NULL DEFAULT '',
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_webhook_deliveries ON webhook_deliveries(webhook_id)`,
	`CREATE TABLE IF NOT EXISTS webhook_event_outbox (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    event TEXT NOT NULL,
	    payload TEXT NOT NULL,
	    -- Retained during rolling deploys; normalized targets are canonical.
	    webhook_ids TEXT NOT NULL DEFAULT '',
	    attempts BIGINT NOT NULL DEFAULT 0,
	    available_at TEXT NOT NULL,
	    locked_at TEXT,
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
	)`,
	`CREATE TABLE IF NOT EXISTS webhook_event_targets (
	    event_id BIGINT NOT NULL,
	    webhook_id BIGINT NOT NULL,
	    PRIMARY KEY (event_id, webhook_id),
	    FOREIGN KEY (event_id) REFERENCES webhook_event_outbox(id) ON DELETE CASCADE,
	    FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE
	)`,
	`DO $$
	DECLARE
	    event_row RECORD;
	    target_id TEXT;
	BEGIN
	    IF EXISTS (
	        SELECT 1 FROM information_schema.columns
	        WHERE table_schema = current_schema()
	          AND table_name = 'webhook_event_outbox' AND column_name = 'webhook_ids'
	    ) THEN
	        FOR event_row IN EXECUTE 'SELECT id, webhook_ids FROM webhook_event_outbox' LOOP
	            FOREACH target_id IN ARRAY string_to_array(event_row.webhook_ids, ',') LOOP
	                IF target_id <> '' THEN
	                    INSERT INTO webhook_event_targets (event_id, webhook_id)
	                    SELECT event_row.id, target_id::BIGINT
	                    WHERE EXISTS (SELECT 1 FROM webhooks WHERE id = target_id::BIGINT)
	                    ON CONFLICT DO NOTHING;
	                END IF;
	            END LOOP;
	        END LOOP;
	    END IF;
	END $$`,
	`CREATE INDEX IF NOT EXISTS idx_webhook_event_claim ON webhook_event_outbox(available_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_webhook_event_targets_webhook ON webhook_event_targets(webhook_id)`,
	`CREATE TABLE IF NOT EXISTS webhook_delivery_queue (
	    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    team_id BIGINT NOT NULL,
	    webhook_id BIGINT NOT NULL,
	    source_event_id BIGINT,
	    event TEXT NOT NULL,
	    payload TEXT NOT NULL,
	    attempts BIGINT NOT NULL DEFAULT 0,
	    available_at TEXT NOT NULL,
	    locked_at TEXT,
	    created_at TEXT NOT NULL,
	    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
	    FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_webhook_queue_claim ON webhook_delivery_queue(available_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_webhook_queue_webhook ON webhook_delivery_queue(webhook_id)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_webhook_queue_source ON webhook_delivery_queue(source_event_id, webhook_id) WHERE source_event_id IS NOT NULL`,
}
